name: Publish artifacts to github
description: "Publish artifacts to github"

inputs:
  staging-folder:
    description: ""
    required: false
    default: staging
  target-folder:
    description: ""
    required: false
    default: github
  release-notes:
    description: "Release notes"
    required: true
  github-token:
    description: "Github auth token"
    required: true
  artifact-version:
    description: "Version of the artifact to release"
    required: true
  build-name-number:
    description: "String containing build name, number and jdk versions"
    required: true

runs:
  using: "composite"
  steps:
    - name: Debug publish to github
      shell: bash
      run: |
        echo "${{ inputs.staging-folder }}"
        echo "${{ inputs.target-folder }}"
        echo "${{ inputs.artifact-version }}"
        echo "${{ inputs.release-notes }}"
        echo "${{ inputs.build-name-number }}"

    - id: get-artifact-version
      shell: bash
      run: |
        VERSION="${{ inputs.artifact-version }}"
        echo "artifact-version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Create upload archive for github
      id: create-artifact
      shell: bash
      run: |
        src="${{ inputs.staging-folder }}"
        dest="${{ inputs.target-folder }}"

        find "$src" -type f \
          -exec cp {} "$dest" \;

    # Listing staged artifacts to be uploaded
    - id: get-github-release-artifact-names
      working-directory: ${{ inputs.target-folder }}
      shell: bash
      run: |
        ARTIFACTS=$(ls | sed "s|^|${{ inputs.target-folder }}/|")

        echo "release-artifacts<<EOF" >> $GITHUB_OUTPUT
        echo "${ARTIFACTS}" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Debug show content of the upload archive
      shell: bash
      run: |
        pwd
        ls ${{ inputs.target-folder }} | sed 's/^//' 

    - name: Debug GitHub publish input
      shell: bash
      working-directory: ${{ inputs.target-folder }}
      run: |
        echo "working directory: ${{ inputs.target-folder }}"
        echo "tag name: Release ${{ steps.get-artifact-version.outputs.artifact-version }}"
        echo "body: Changes for release ${{ steps.get-artifact-version.outputs.artifact-version }}"
        echo "body: ${{ inputs.release-notes }}"
        echo "files: ${{ steps.get-github-release-artifact-names.outputs.release-artifacts }}"

    - name: Publish release to github
      uses: step-security/action-gh-release@5f6a6ab53a5a2c000ff3a16fad038291e5b97ce7 # v2.4.2
      with:
        token: ${{ inputs.github-token }}
        tag_name: ${{ steps.get-artifact-version.outputs.artifact-version }}
        body: |
          Changes for release ${{ steps.get-artifact-version.outputs.artifact-version }}
          ${{ inputs.release-notes }}
        draft: true
        prerelease: false
        files: ${{ steps.get-github-release-artifact-names.outputs.release-artifacts }}
