name: Get version
description: Detects if build is a snapshot and gets the release or snapshot version

runs:
  using: composite
  steps:
    # Checking if this particular build is a snapshot build
    - name: Detect if snapshot
      id: get-is-snapshot
      shell: bash
      run: |
        # Check if tagged with release or release candidate
        TAG=$(git describe --exact-match --tags HEAD 2>/dev/null || echo "")
        echo "Detected Git tag: '$TAG'"
        
        # Define regex patterns
        RE_PROD='^v?[0-9]+\.[0-9]+\.[0-9]+$'
        RE_RC='^v?[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$'
        
        if [[ "$TAG" =~ $RE_PROD ]]; then
          echo "Production release tag detected: $TAG"
          echo "is-snapshot=false" >> $GITHUB_OUTPUT
          exit 0
        elif [[ "$TAG" =~ $RE_RC ]]; then
          echo "Release candidate tag detected: $TAG"
          echo "is-snapshot=false" >> $GITHUB_OUTPUT
          exit 0
        else
          echo "No matching tag found"
          echo "is-snapshot=true" >> $GITHUB_OUTPUT
        fi
        
        # Checking if previous commit contains pom.xml. This should always return true
        COMMIT_REF="HEAD~1"
        if ! git show "${COMMIT_REF}:pom.xml" &>/dev/null; then
          echo "Error: pom.xml not found in commit ${COMMIT_REF}"
          echo "is-snapshot='true'" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Getting previous version
        OLD_VERSIONS=$(git show "${COMMIT_REF}:pom.xml" | sed -n '0,/<version>/ s/.*<version>\([^<]*\)<\/version>.*/\1/p')

        # Getting current version
        NEW_VERSIONS=$(sed -n '0,/<version>/ s/.*<version>\([^<]*\)<\/version>.*/\1/p' pom.xml)

        echo "old versions: ${OLD_VERSIONS}, new versions: ${NEW_VERSIONS}"
        # Compare the extracted versions. CI will not commit snapshot version.
        if [[ "${OLD_VERSIONS}" != "${NEW_VERSIONS}" ]]; then
          echo "is-snapshot=false" >> $GITHUB_OUTPUT
        else
          echo "is-snapshot=true" >> $GITHUB_OUTPUT
        fi

    - name: Get release or snapshot-version
      id: get-release-version
      shell: bash
      run: |
        IS_SNAPSHOT=${{ steps.get-is-snapshot.outputs.is-snapshot }}
        if [ $IS_SNAPSHOT == "true" ];then
          echo release-version="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)-SNAPSHOT_$GITHUB_SHA" >> $GITHUB_OUTPUT
        else
          echo release-version="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
        fi

outputs:
  is-snapshot:
    description: Whether this is a snapshot build
    value: ${{ steps.get-is-snapshot.outputs.is-snapshot }}
  release-version:
    description: The release or snapshot version
    value: ${{ steps.get-release-version.outputs.release-version }}